default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: expensify_development

test:
  <<: *default
  database: expensify_test

production:
  <<: *default
  database: expensify_production
  username: expensify
  password: <%= ENV['EXPENSIFY_DATABASE_PASSWORD'] %>
